import java.io.Serializable;
import java.util.Date;

/**
 * 견적테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EstimateMembervo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 번호. */
	private Integer unq;

	/** 여행타입. */
	private String type;

	/** 메일주소. */
	private String email;

	/** 이름. */
	private String name;

	/** 휴대번호. */
	private String phone;

	/** 인원수. */
	private Integer person;

	/** 가격대. */
	private String money;

	/** 통화가능시간. */
	private String ptime;

	/** 선호지역. */
	private String floc;

	/** 출발일. */
	private Date sdate;

	/** 도착일. */
	private Date edate;

	/** 출발일변경여부. */
	private String schange;

	/** 항공. */
	private String airline;

	/** 숙박시설종류. */
	private String stay;

	/** 숙박지명. */
	private String stayname;

	/** 고객요청사항. */
	private String req;

	/** 등록일. */
	private Date rdate;

	/** 처리여부. */
	private String result;

	/** 담당자. */
	private String manager;

	/**
	 * 생성자.
	 */
	public EstimateMembervo() {
	}

	/**
	 * 번호을 설정합니다..
	 * 
	 * @param unq
	 *            번호
	 */
	public void setUnq(Integer unq) {
		this.unq = unq;
	}

	/**
	 * 번호을 가져옵니다..
	 * 
	 * @return 번호
	 */
	public Integer getUnq() {
		return this.unq;
	}

	/**
	 * 여행타입을 설정합니다..
	 * 
	 * @param type
	 *            여행타입
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * 여행타입을 가져옵니다..
	 * 
	 * @return 여행타입
	 */
	public String getType() {
		return this.type;
	}

	/**
	 * 메일주소을 설정합니다..
	 * 
	 * @param email
	 *            메일주소
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * 메일주소을 가져옵니다..
	 * 
	 * @return 메일주소
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * 이름을 설정합니다..
	 * 
	 * @param name
	 *            이름
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 이름을 가져옵니다..
	 * 
	 * @return 이름
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 휴대번호을 설정합니다..
	 * 
	 * @param phone
	 *            휴대번호
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * 휴대번호을 가져옵니다..
	 * 
	 * @return 휴대번호
	 */
	public String getPhone() {
		return this.phone;
	}

	/**
	 * 인원수을 설정합니다..
	 * 
	 * @param person
	 *            인원수
	 */
	public void setPerson(Integer person) {
		this.person = person;
	}

	/**
	 * 인원수을 가져옵니다..
	 * 
	 * @return 인원수
	 */
	public Integer getPerson() {
		return this.person;
	}

	/**
	 * 가격대을 설정합니다..
	 * 
	 * @param money
	 *            가격대
	 */
	public void setMoney(String money) {
		this.money = money;
	}

	/**
	 * 가격대을 가져옵니다..
	 * 
	 * @return 가격대
	 */
	public String getMoney() {
		return this.money;
	}

	/**
	 * 통화가능시간을 설정합니다..
	 * 
	 * @param ptime
	 *            통화가능시간
	 */
	public void setPtime(String ptime) {
		this.ptime = ptime;
	}

	/**
	 * 통화가능시간을 가져옵니다..
	 * 
	 * @return 통화가능시간
	 */
	public String getPtime() {
		return this.ptime;
	}

	/**
	 * 선호지역을 설정합니다..
	 * 
	 * @param floc
	 *            선호지역
	 */
	public void setFloc(String floc) {
		this.floc = floc;
	}

	/**
	 * 선호지역을 가져옵니다..
	 * 
	 * @return 선호지역
	 */
	public String getFloc() {
		return this.floc;
	}

	/**
	 * 출발일을 설정합니다..
	 * 
	 * @param sdate
	 *            출발일
	 */
	public void setSdate(Date sdate) {
		this.sdate = sdate;
	}

	/**
	 * 출발일을 가져옵니다..
	 * 
	 * @return 출발일
	 */
	public Date getSdate() {
		return this.sdate;
	}

	/**
	 * 도착일을 설정합니다..
	 * 
	 * @param edate
	 *            도착일
	 */
	public void setEdate(Date edate) {
		this.edate = edate;
	}

	/**
	 * 도착일을 가져옵니다..
	 * 
	 * @return 도착일
	 */
	public Date getEdate() {
		return this.edate;
	}

	/**
	 * 출발일변경여부을 설정합니다..
	 * 
	 * @param schange
	 *            출발일변경여부
	 */
	public void setSchange(String schange) {
		this.schange = schange;
	}

	/**
	 * 출발일변경여부을 가져옵니다..
	 * 
	 * @return 출발일변경여부
	 */
	public String getSchange() {
		return this.schange;
	}

	/**
	 * 항공을 설정합니다..
	 * 
	 * @param airline
	 *            항공
	 */
	public void setAirline(String airline) {
		this.airline = airline;
	}

	/**
	 * 항공을 가져옵니다..
	 * 
	 * @return 항공
	 */
	public String getAirline() {
		return this.airline;
	}

	/**
	 * 숙박시설종류을 설정합니다..
	 * 
	 * @param stay
	 *            숙박시설종류
	 */
	public void setStay(String stay) {
		this.stay = stay;
	}

	/**
	 * 숙박시설종류을 가져옵니다..
	 * 
	 * @return 숙박시설종류
	 */
	public String getStay() {
		return this.stay;
	}

	/**
	 * 숙박지명을 설정합니다..
	 * 
	 * @param stayname
	 *            숙박지명
	 */
	public void setStayname(String stayname) {
		this.stayname = stayname;
	}

	/**
	 * 숙박지명을 가져옵니다..
	 * 
	 * @return 숙박지명
	 */
	public String getStayname() {
		return this.stayname;
	}

	/**
	 * 고객요청사항을 설정합니다..
	 * 
	 * @param req
	 *            고객요청사항
	 */
	public void setReq(String req) {
		this.req = req;
	}

	/**
	 * 고객요청사항을 가져옵니다..
	 * 
	 * @return 고객요청사항
	 */
	public String getReq() {
		return this.req;
	}

	/**
	 * 등록일을 설정합니다..
	 * 
	 * @param rdate
	 *            등록일
	 */
	public void setRdate(Date rdate) {
		this.rdate = rdate;
	}

	/**
	 * 등록일을 가져옵니다..
	 * 
	 * @return 등록일
	 */
	public Date getRdate() {
		return this.rdate;
	}

	/**
	 * 처리여부을 설정합니다..
	 * 
	 * @param result
	 *            처리여부
	 */
	public void setResult(String result) {
		this.result = result;
	}

	/**
	 * 처리여부을 가져옵니다..
	 * 
	 * @return 처리여부
	 */
	public String getResult() {
		return this.result;
	}

	/**
	 * 담당자을 설정합니다..
	 * 
	 * @param manager
	 *            담당자
	 */
	public void setManager(String manager) {
		this.manager = manager;
	}

	/**
	 * 담당자을 가져옵니다..
	 * 
	 * @return 담당자
	 */
	public String getManager() {
		return this.manager;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((unq == null) ? 0 : unq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EstimateMembervo other = (EstimateMembervo) obj;
		if (unq == null) {
			if (other.unq != null) {
				return false;
			}
		} else if (!unq.equals(other.unq)) {
			return false;
		}
		return true;
	}

}
