import java.io.Serializable;
import java.util.Date;

/**
 * 상품테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class GoodsMembervo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 번호. */
	private Integer unq;

	/** 여행상품명. */
	private String title;

	/** 큰구분 상품카테고리. */
	private String gubun;

	/** 국가. */
	private String nation;

	/** 도시. */
	private String city;

	/** 상품가격. */
	private Integer price;

	/** 출발일. */
	private Date sdate;

	/** 도착일. */
	private Date edate;

	/** 여행기간. */
	private String period;

	/** 간략일정. */
	private String schd;

	/** 상품상세정보. */
	private String detail1;

	/** 상세정보2. */
	private String detail2;

	/** 이용항공. */
	private String airline;

	/** 인원수. */
	private Integer person;

	/** 상품번호. */
	private String code;

	/**
	 * 생성자.
	 */
	public GoodsMembervo() {
	}

	/**
	 * 번호을 설정합니다..
	 * 
	 * @param unq
	 *            번호
	 */
	public void setUnq(Integer unq) {
		this.unq = unq;
	}

	/**
	 * 번호을 가져옵니다..
	 * 
	 * @return 번호
	 */
	public Integer getUnq() {
		return this.unq;
	}

	/**
	 * 여행상품명을 설정합니다..
	 * 
	 * @param title
	 *            여행상품명
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * 여행상품명을 가져옵니다..
	 * 
	 * @return 여행상품명
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * 큰구분 상품카테고리을 설정합니다..
	 * 
	 * @param gubun
	 *            큰구분 상품카테고리
	 */
	public void setGubun(String gubun) {
		this.gubun = gubun;
	}

	/**
	 * 큰구분 상품카테고리을 가져옵니다..
	 * 
	 * @return 큰구분 상품카테고리
	 */
	public String getGubun() {
		return this.gubun;
	}

	/**
	 * 국가을 설정합니다..
	 * 
	 * @param nation
	 *            국가
	 */
	public void setNation(String nation) {
		this.nation = nation;
	}

	/**
	 * 국가을 가져옵니다..
	 * 
	 * @return 국가
	 */
	public String getNation() {
		return this.nation;
	}

	/**
	 * 도시을 설정합니다..
	 * 
	 * @param city
	 *            도시
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * 도시을 가져옵니다..
	 * 
	 * @return 도시
	 */
	public String getCity() {
		return this.city;
	}

	/**
	 * 상품가격을 설정합니다..
	 * 
	 * @param price
	 *            상품가격
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * 상품가격을 가져옵니다..
	 * 
	 * @return 상품가격
	 */
	public Integer getPrice() {
		return this.price;
	}

	/**
	 * 출발일을 설정합니다..
	 * 
	 * @param sdate
	 *            출발일
	 */
	public void setSdate(Date sdate) {
		this.sdate = sdate;
	}

	/**
	 * 출발일을 가져옵니다..
	 * 
	 * @return 출발일
	 */
	public Date getSdate() {
		return this.sdate;
	}

	/**
	 * 도착일을 설정합니다..
	 * 
	 * @param edate
	 *            도착일
	 */
	public void setEdate(Date edate) {
		this.edate = edate;
	}

	/**
	 * 도착일을 가져옵니다..
	 * 
	 * @return 도착일
	 */
	public Date getEdate() {
		return this.edate;
	}

	/**
	 * 여행기간을 설정합니다..
	 * 
	 * @param period
	 *            여행기간
	 */
	public void setPeriod(String period) {
		this.period = period;
	}

	/**
	 * 여행기간을 가져옵니다..
	 * 
	 * @return 여행기간
	 */
	public String getPeriod() {
		return this.period;
	}

	/**
	 * 간략일정을 설정합니다..
	 * 
	 * @param schd
	 *            간략일정
	 */
	public void setSchd(String schd) {
		this.schd = schd;
	}

	/**
	 * 간략일정을 가져옵니다..
	 * 
	 * @return 간략일정
	 */
	public String getSchd() {
		return this.schd;
	}

	/**
	 * 상품상세정보을 설정합니다..
	 * 
	 * @param detail1
	 *            상품상세정보
	 */
	public void setDetail1(String detail1) {
		this.detail1 = detail1;
	}

	/**
	 * 상품상세정보을 가져옵니다..
	 * 
	 * @return 상품상세정보
	 */
	public String getDetail1() {
		return this.detail1;
	}

	/**
	 * 상세정보2을 설정합니다..
	 * 
	 * @param detail2
	 *            상세정보2
	 */
	public void setDetail2(String detail2) {
		this.detail2 = detail2;
	}

	/**
	 * 상세정보2을 가져옵니다..
	 * 
	 * @return 상세정보2
	 */
	public String getDetail2() {
		return this.detail2;
	}

	/**
	 * 이용항공을 설정합니다..
	 * 
	 * @param airline
	 *            이용항공
	 */
	public void setAirline(String airline) {
		this.airline = airline;
	}

	/**
	 * 이용항공을 가져옵니다..
	 * 
	 * @return 이용항공
	 */
	public String getAirline() {
		return this.airline;
	}

	/**
	 * 인원수을 설정합니다..
	 * 
	 * @param person
	 *            인원수
	 */
	public void setPerson(Integer person) {
		this.person = person;
	}

	/**
	 * 인원수을 가져옵니다..
	 * 
	 * @return 인원수
	 */
	public Integer getPerson() {
		return this.person;
	}

	/**
	 * 상품번호을 설정합니다..
	 * 
	 * @param code
	 *            상품번호
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * 상품번호을 가져옵니다..
	 * 
	 * @return 상품번호
	 */
	public String getCode() {
		return this.code;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((unq == null) ? 0 : unq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		GoodsMembervo other = (GoodsMembervo) obj;
		if (unq == null) {
			if (other.unq != null) {
				return false;
			}
		} else if (!unq.equals(other.unq)) {
			return false;
		}
		return true;
	}

}
