import java.io.Serializable;
import java.util.Date;

/**
 * 회원테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class MemberMembervo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 번호. */
	private Integer unq;

	/** 회원아이디. */
	private String id;

	/** 패스워드. */
	private String pwd;

	/** 회원이름. */
	private String name;

	/** 성별. */
	private String gender;

	/** 메일주소. */
	private String email;

	/** 휴대번호. */
	private String phone;

	/** 자택전화. */
	private String tel;

	/** 기본주소1. */
	private String addr11;

	/** 상세주소1. */
	private String addr12;

	/** 우편번호1. */
	private String postnum1;

	/** 신주소2. */
	private String addr21;

	/** 상세주소2. */
	private String addr22;

	/** 우편번호2. */
	private String postnum2;

	/** 직업. */
	private String job;

	/** 생년월일. */
	private Date birthday;

	/** 결혼여부. */
	private String marry;

	/** 결혼기념. */
	private Date mdate;

	/** 선호지역. */
	private String floc;

	/** 포인트. */
	private Integer point;

	/** 메일수신동의. */
	private String agree1;

	/** 휴대폰수신동의. */
	private String agree2;

	/**
	 * 생성자.
	 */
	public MemberMembervo() {
	}

	/**
	 * 번호을 설정합니다..
	 * 
	 * @param unq
	 *            번호
	 */
	public void setUnq(Integer unq) {
		this.unq = unq;
	}

	/**
	 * 번호을 가져옵니다..
	 * 
	 * @return 번호
	 */
	public Integer getUnq() {
		return this.unq;
	}

	/**
	 * 회원아이디을 설정합니다..
	 * 
	 * @param id
	 *            회원아이디
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * 회원아이디을 가져옵니다..
	 * 
	 * @return 회원아이디
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * 패스워드을 설정합니다..
	 * 
	 * @param pwd
	 *            패스워드
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * 패스워드을 가져옵니다..
	 * 
	 * @return 패스워드
	 */
	public String getPwd() {
		return this.pwd;
	}

	/**
	 * 회원이름을 설정합니다..
	 * 
	 * @param name
	 *            회원이름
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 회원이름을 가져옵니다..
	 * 
	 * @return 회원이름
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 성별을 설정합니다..
	 * 
	 * @param gender
	 *            성별
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * 성별을 가져옵니다..
	 * 
	 * @return 성별
	 */
	public String getGender() {
		return this.gender;
	}

	/**
	 * 메일주소을 설정합니다..
	 * 
	 * @param email
	 *            메일주소
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * 메일주소을 가져옵니다..
	 * 
	 * @return 메일주소
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * 휴대번호을 설정합니다..
	 * 
	 * @param phone
	 *            휴대번호
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * 휴대번호을 가져옵니다..
	 * 
	 * @return 휴대번호
	 */
	public String getPhone() {
		return this.phone;
	}

	/**
	 * 자택전화을 설정합니다..
	 * 
	 * @param tel
	 *            자택전화
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * 자택전화을 가져옵니다..
	 * 
	 * @return 자택전화
	 */
	public String getTel() {
		return this.tel;
	}

	/**
	 * 기본주소1을 설정합니다..
	 * 
	 * @param addr11
	 *            기본주소1
	 */
	public void setAddr11(String addr11) {
		this.addr11 = addr11;
	}

	/**
	 * 기본주소1을 가져옵니다..
	 * 
	 * @return 기본주소1
	 */
	public String getAddr11() {
		return this.addr11;
	}

	/**
	 * 상세주소1을 설정합니다..
	 * 
	 * @param addr12
	 *            상세주소1
	 */
	public void setAddr12(String addr12) {
		this.addr12 = addr12;
	}

	/**
	 * 상세주소1을 가져옵니다..
	 * 
	 * @return 상세주소1
	 */
	public String getAddr12() {
		return this.addr12;
	}

	/**
	 * 우편번호1을 설정합니다..
	 * 
	 * @param postnum1
	 *            우편번호1
	 */
	public void setPostnum1(String postnum1) {
		this.postnum1 = postnum1;
	}

	/**
	 * 우편번호1을 가져옵니다..
	 * 
	 * @return 우편번호1
	 */
	public String getPostnum1() {
		return this.postnum1;
	}

	/**
	 * 신주소2을 설정합니다..
	 * 
	 * @param addr21
	 *            신주소2
	 */
	public void setAddr21(String addr21) {
		this.addr21 = addr21;
	}

	/**
	 * 신주소2을 가져옵니다..
	 * 
	 * @return 신주소2
	 */
	public String getAddr21() {
		return this.addr21;
	}

	/**
	 * 상세주소2을 설정합니다..
	 * 
	 * @param addr22
	 *            상세주소2
	 */
	public void setAddr22(String addr22) {
		this.addr22 = addr22;
	}

	/**
	 * 상세주소2을 가져옵니다..
	 * 
	 * @return 상세주소2
	 */
	public String getAddr22() {
		return this.addr22;
	}

	/**
	 * 우편번호2을 설정합니다..
	 * 
	 * @param postnum2
	 *            우편번호2
	 */
	public void setPostnum2(String postnum2) {
		this.postnum2 = postnum2;
	}

	/**
	 * 우편번호2을 가져옵니다..
	 * 
	 * @return 우편번호2
	 */
	public String getPostnum2() {
		return this.postnum2;
	}

	/**
	 * 직업을 설정합니다..
	 * 
	 * @param job
	 *            직업
	 */
	public void setJob(String job) {
		this.job = job;
	}

	/**
	 * 직업을 가져옵니다..
	 * 
	 * @return 직업
	 */
	public String getJob() {
		return this.job;
	}

	/**
	 * 생년월일을 설정합니다..
	 * 
	 * @param birthday
	 *            생년월일
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * 생년월일을 가져옵니다..
	 * 
	 * @return 생년월일
	 */
	public Date getBirthday() {
		return this.birthday;
	}

	/**
	 * 결혼여부을 설정합니다..
	 * 
	 * @param marry
	 *            결혼여부
	 */
	public void setMarry(String marry) {
		this.marry = marry;
	}

	/**
	 * 결혼여부을 가져옵니다..
	 * 
	 * @return 결혼여부
	 */
	public String getMarry() {
		return this.marry;
	}

	/**
	 * 결혼기념을 설정합니다..
	 * 
	 * @param mdate
	 *            결혼기념
	 */
	public void setMdate(Date mdate) {
		this.mdate = mdate;
	}

	/**
	 * 결혼기념을 가져옵니다..
	 * 
	 * @return 결혼기념
	 */
	public Date getMdate() {
		return this.mdate;
	}

	/**
	 * 선호지역을 설정합니다..
	 * 
	 * @param floc
	 *            선호지역
	 */
	public void setFloc(String floc) {
		this.floc = floc;
	}

	/**
	 * 선호지역을 가져옵니다..
	 * 
	 * @return 선호지역
	 */
	public String getFloc() {
		return this.floc;
	}

	/**
	 * 포인트을 설정합니다..
	 * 
	 * @param point
	 *            포인트
	 */
	public void setPoint(Integer point) {
		this.point = point;
	}

	/**
	 * 포인트을 가져옵니다..
	 * 
	 * @return 포인트
	 */
	public Integer getPoint() {
		return this.point;
	}

	/**
	 * 메일수신동의을 설정합니다..
	 * 
	 * @param agree1
	 *            메일수신동의
	 */
	public void setAgree1(String agree1) {
		this.agree1 = agree1;
	}

	/**
	 * 메일수신동의을 가져옵니다..
	 * 
	 * @return 메일수신동의
	 */
	public String getAgree1() {
		return this.agree1;
	}

	/**
	 * 휴대폰수신동의을 설정합니다..
	 * 
	 * @param agree2
	 *            휴대폰수신동의
	 */
	public void setAgree2(String agree2) {
		this.agree2 = agree2;
	}

	/**
	 * 휴대폰수신동의을 가져옵니다..
	 * 
	 * @return 휴대폰수신동의
	 */
	public String getAgree2() {
		return this.agree2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((unq == null) ? 0 : unq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		MemberMembervo other = (MemberMembervo) obj;
		if (unq == null) {
			if (other.unq != null) {
				return false;
			}
		} else if (!unq.equals(other.unq)) {
			return false;
		}
		return true;
	}

}
