import java.io.Serializable;
import java.util.Date;

/**
 * 포인트 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PointMembervo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 번호. */
	private Integer unq;

	/** 사용포인트. */
	private Integer usepoint;

	/** 사용일자. */
	private Date udate;

	/** 아이디. */
	private String userid;

	/** 획득방법. */
	private String get;

	/** 상품명. */
	private String gtitle;

	/**
	 * 생성자.
	 */
	public PointMembervo() {
	}

	/**
	 * 번호을 설정합니다..
	 * 
	 * @param unq
	 *            번호
	 */
	public void setUnq(Integer unq) {
		this.unq = unq;
	}

	/**
	 * 번호을 가져옵니다..
	 * 
	 * @return 번호
	 */
	public Integer getUnq() {
		return this.unq;
	}

	/**
	 * 사용포인트을 설정합니다..
	 * 
	 * @param usepoint
	 *            사용포인트
	 */
	public void setUsepoint(Integer usepoint) {
		this.usepoint = usepoint;
	}

	/**
	 * 사용포인트을 가져옵니다..
	 * 
	 * @return 사용포인트
	 */
	public Integer getUsepoint() {
		return this.usepoint;
	}

	/**
	 * 사용일자을 설정합니다..
	 * 
	 * @param udate
	 *            사용일자
	 */
	public void setUdate(Date udate) {
		this.udate = udate;
	}

	/**
	 * 사용일자을 가져옵니다..
	 * 
	 * @return 사용일자
	 */
	public Date getUdate() {
		return this.udate;
	}

	/**
	 * 아이디을 설정합니다..
	 * 
	 * @param userid
	 *            아이디
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * 아이디을 가져옵니다..
	 * 
	 * @return 아이디
	 */
	public String getUserid() {
		return this.userid;
	}

	/**
	 * 획득방법을 설정합니다..
	 * 
	 * @param get
	 *            획득방법
	 */
	public void setGet(String get) {
		this.get = get;
	}

	/**
	 * 획득방법을 가져옵니다..
	 * 
	 * @return 획득방법
	 */
	public String getGet() {
		return this.get;
	}

	/**
	 * 상품명을 설정합니다..
	 * 
	 * @param gtitle
	 *            상품명
	 */
	public void setGtitle(String gtitle) {
		this.gtitle = gtitle;
	}

	/**
	 * 상품명을 가져옵니다..
	 * 
	 * @return 상품명
	 */
	public String getGtitle() {
		return this.gtitle;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((unq == null) ? 0 : unq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		PointMembervo other = (PointMembervo) obj;
		if (unq == null) {
			if (other.unq != null) {
				return false;
			}
		} else if (!unq.equals(other.unq)) {
			return false;
		}
		return true;
	}

}
