import java.io.Serializable;
import java.util.Date;

/**
 * 예약테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ReservMembervo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 번호. */
	private Integer unq;

	/** 예약번호. */
	private String rsvno;

	/** 예약일. */
	private Date rsvdate;

	/** 성인예약. */
	private Integer rsvanum;

	/** 어린이예약. */
	private Integer rsvcnum;

	/** 유아예약인원. */
	private Integer rsvbnum;

	/** 상품명. */
	private String gtitle;

	/** 출발일. */
	private Date sdate;

	/** 도착일. */
	private Date edate;

	/** 항공. */
	private String airline;

	/** 가격. */
	private Integer price;

	/** 이름. */
	private String name;

	/** 영문명. */
	private String ename;

	/** 생년월일. */
	private Date birthday;

	/** 결제방법. */
	private String payment;

	/** 처리여부. */
	private String result;

	/** 취소/환불. */
	private String cancel;

	/**
	 * 생성자.
	 */
	public ReservMembervo() {
	}

	/**
	 * 번호을 설정합니다..
	 * 
	 * @param unq
	 *            번호
	 */
	public void setUnq(Integer unq) {
		this.unq = unq;
	}

	/**
	 * 번호을 가져옵니다..
	 * 
	 * @return 번호
	 */
	public Integer getUnq() {
		return this.unq;
	}

	/**
	 * 예약번호을 설정합니다..
	 * 
	 * @param rsvno
	 *            예약번호
	 */
	public void setRsvno(String rsvno) {
		this.rsvno = rsvno;
	}

	/**
	 * 예약번호을 가져옵니다..
	 * 
	 * @return 예약번호
	 */
	public String getRsvno() {
		return this.rsvno;
	}

	/**
	 * 예약일을 설정합니다..
	 * 
	 * @param rsvdate
	 *            예약일
	 */
	public void setRsvdate(Date rsvdate) {
		this.rsvdate = rsvdate;
	}

	/**
	 * 예약일을 가져옵니다..
	 * 
	 * @return 예약일
	 */
	public Date getRsvdate() {
		return this.rsvdate;
	}

	/**
	 * 성인예약을 설정합니다..
	 * 
	 * @param rsvanum
	 *            성인예약
	 */
	public void setRsvanum(Integer rsvanum) {
		this.rsvanum = rsvanum;
	}

	/**
	 * 성인예약을 가져옵니다..
	 * 
	 * @return 성인예약
	 */
	public Integer getRsvanum() {
		return this.rsvanum;
	}

	/**
	 * 어린이예약을 설정합니다..
	 * 
	 * @param rsvcnum
	 *            어린이예약
	 */
	public void setRsvcnum(Integer rsvcnum) {
		this.rsvcnum = rsvcnum;
	}

	/**
	 * 어린이예약을 가져옵니다..
	 * 
	 * @return 어린이예약
	 */
	public Integer getRsvcnum() {
		return this.rsvcnum;
	}

	/**
	 * 유아예약인원을 설정합니다..
	 * 
	 * @param rsvbnum
	 *            유아예약인원
	 */
	public void setRsvbnum(Integer rsvbnum) {
		this.rsvbnum = rsvbnum;
	}

	/**
	 * 유아예약인원을 가져옵니다..
	 * 
	 * @return 유아예약인원
	 */
	public Integer getRsvbnum() {
		return this.rsvbnum;
	}

	/**
	 * 상품명을 설정합니다..
	 * 
	 * @param gtitle
	 *            상품명
	 */
	public void setGtitle(String gtitle) {
		this.gtitle = gtitle;
	}

	/**
	 * 상품명을 가져옵니다..
	 * 
	 * @return 상품명
	 */
	public String getGtitle() {
		return this.gtitle;
	}

	/**
	 * 출발일을 설정합니다..
	 * 
	 * @param sdate
	 *            출발일
	 */
	public void setSdate(Date sdate) {
		this.sdate = sdate;
	}

	/**
	 * 출발일을 가져옵니다..
	 * 
	 * @return 출발일
	 */
	public Date getSdate() {
		return this.sdate;
	}

	/**
	 * 도착일을 설정합니다..
	 * 
	 * @param edate
	 *            도착일
	 */
	public void setEdate(Date edate) {
		this.edate = edate;
	}

	/**
	 * 도착일을 가져옵니다..
	 * 
	 * @return 도착일
	 */
	public Date getEdate() {
		return this.edate;
	}

	/**
	 * 항공을 설정합니다..
	 * 
	 * @param airline
	 *            항공
	 */
	public void setAirline(String airline) {
		this.airline = airline;
	}

	/**
	 * 항공을 가져옵니다..
	 * 
	 * @return 항공
	 */
	public String getAirline() {
		return this.airline;
	}

	/**
	 * 가격을 설정합니다..
	 * 
	 * @param price
	 *            가격
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * 가격을 가져옵니다..
	 * 
	 * @return 가격
	 */
	public Integer getPrice() {
		return this.price;
	}

	/**
	 * 이름을 설정합니다..
	 * 
	 * @param name
	 *            이름
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 이름을 가져옵니다..
	 * 
	 * @return 이름
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 영문명을 설정합니다..
	 * 
	 * @param ename
	 *            영문명
	 */
	public void setEname(String ename) {
		this.ename = ename;
	}

	/**
	 * 영문명을 가져옵니다..
	 * 
	 * @return 영문명
	 */
	public String getEname() {
		return this.ename;
	}

	/**
	 * 생년월일을 설정합니다..
	 * 
	 * @param birthday
	 *            생년월일
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * 생년월일을 가져옵니다..
	 * 
	 * @return 생년월일
	 */
	public Date getBirthday() {
		return this.birthday;
	}

	/**
	 * 결제방법을 설정합니다..
	 * 
	 * @param payment
	 *            결제방법
	 */
	public void setPayment(String payment) {
		this.payment = payment;
	}

	/**
	 * 결제방법을 가져옵니다..
	 * 
	 * @return 결제방법
	 */
	public String getPayment() {
		return this.payment;
	}

	/**
	 * 처리여부을 설정합니다..
	 * 
	 * @param result
	 *            처리여부
	 */
	public void setResult(String result) {
		this.result = result;
	}

	/**
	 * 처리여부을 가져옵니다..
	 * 
	 * @return 처리여부
	 */
	public String getResult() {
		return this.result;
	}

	/**
	 * 취소/환불을 설정합니다..
	 * 
	 * @param cancel
	 *            취소/환불
	 */
	public void setCancel(String cancel) {
		this.cancel = cancel;
	}

	/**
	 * 취소/환불을 가져옵니다..
	 * 
	 * @return 취소/환불
	 */
	public String getCancel() {
		return this.cancel;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((unq == null) ? 0 : unq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ReservMembervo other = (ReservMembervo) obj;
		if (unq == null) {
			if (other.unq != null) {
				return false;
			}
		} else if (!unq.equals(other.unq)) {
			return false;
		}
		return true;
	}

}
