import java.io.Serializable;
import java.util.Date;

/**
 * 항공권구매 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TicketMembervo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 번호. */
	private Integer unq;

	/** 출발지. */
	private String sloc;

	/** 도착지. */
	private String eloc;

	/** 도착일. */
	private Date edate;

	/** 출발일. */
	private Date sdate;

	/** 성인예약. */
	private Integer rsvanum;

	/** 유아예약인원. */
	private Integer rsvbnum;

	/** 어린이예약. */
	private Integer rsvcnum;

	/** 왕복편도여부. */
	private String return;

	/** 항공사. */
	private String airline;

	/** 가격. */
	private Integer price;

	/** 요금조건. */
	private String people;

	/** 경유여부. */
	private String route;

	/** 출발시간. */
	private String stime;

	/** 도착시간. */
	private String etime;

	/**
	 * 생성자.
	 */
	public TicketMembervo() {
	}

	/**
	 * 번호을 설정합니다..
	 * 
	 * @param unq
	 *            번호
	 */
	public void setUnq(Integer unq) {
		this.unq = unq;
	}

	/**
	 * 번호을 가져옵니다..
	 * 
	 * @return 번호
	 */
	public Integer getUnq() {
		return this.unq;
	}

	/**
	 * 출발지을 설정합니다..
	 * 
	 * @param sloc
	 *            출발지
	 */
	public void setSloc(String sloc) {
		this.sloc = sloc;
	}

	/**
	 * 출발지을 가져옵니다..
	 * 
	 * @return 출발지
	 */
	public String getSloc() {
		return this.sloc;
	}

	/**
	 * 도착지을 설정합니다..
	 * 
	 * @param eloc
	 *            도착지
	 */
	public void setEloc(String eloc) {
		this.eloc = eloc;
	}

	/**
	 * 도착지을 가져옵니다..
	 * 
	 * @return 도착지
	 */
	public String getEloc() {
		return this.eloc;
	}

	/**
	 * 도착일을 설정합니다..
	 * 
	 * @param edate
	 *            도착일
	 */
	public void setEdate(Date edate) {
		this.edate = edate;
	}

	/**
	 * 도착일을 가져옵니다..
	 * 
	 * @return 도착일
	 */
	public Date getEdate() {
		return this.edate;
	}

	/**
	 * 출발일을 설정합니다..
	 * 
	 * @param sdate
	 *            출발일
	 */
	public void setSdate(Date sdate) {
		this.sdate = sdate;
	}

	/**
	 * 출발일을 가져옵니다..
	 * 
	 * @return 출발일
	 */
	public Date getSdate() {
		return this.sdate;
	}

	/**
	 * 성인예약을 설정합니다..
	 * 
	 * @param rsvanum
	 *            성인예약
	 */
	public void setRsvanum(Integer rsvanum) {
		this.rsvanum = rsvanum;
	}

	/**
	 * 성인예약을 가져옵니다..
	 * 
	 * @return 성인예약
	 */
	public Integer getRsvanum() {
		return this.rsvanum;
	}

	/**
	 * 유아예약인원을 설정합니다..
	 * 
	 * @param rsvbnum
	 *            유아예약인원
	 */
	public void setRsvbnum(Integer rsvbnum) {
		this.rsvbnum = rsvbnum;
	}

	/**
	 * 유아예약인원을 가져옵니다..
	 * 
	 * @return 유아예약인원
	 */
	public Integer getRsvbnum() {
		return this.rsvbnum;
	}

	/**
	 * 어린이예약을 설정합니다..
	 * 
	 * @param rsvcnum
	 *            어린이예약
	 */
	public void setRsvcnum(Integer rsvcnum) {
		this.rsvcnum = rsvcnum;
	}

	/**
	 * 어린이예약을 가져옵니다..
	 * 
	 * @return 어린이예약
	 */
	public Integer getRsvcnum() {
		return this.rsvcnum;
	}

	/**
	 * 왕복편도여부을 설정합니다..
	 * 
	 * @param return
	 *            왕복편도여부
	 */
	public void setReturn(String return) {
		this.return = return;
	}

	/**
	 * 왕복편도여부을 가져옵니다..
	 * 
	 * @return 왕복편도여부
	 */
	public String getReturn() {
		return this.return;
	}

	/**
	 * 항공사을 설정합니다..
	 * 
	 * @param airline
	 *            항공사
	 */
	public void setAirline(String airline) {
		this.airline = airline;
	}

	/**
	 * 항공사을 가져옵니다..
	 * 
	 * @return 항공사
	 */
	public String getAirline() {
		return this.airline;
	}

	/**
	 * 가격을 설정합니다..
	 * 
	 * @param price
	 *            가격
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * 가격을 가져옵니다..
	 * 
	 * @return 가격
	 */
	public Integer getPrice() {
		return this.price;
	}

	/**
	 * 요금조건을 설정합니다..
	 * 
	 * @param people
	 *            요금조건
	 */
	public void setPeople(String people) {
		this.people = people;
	}

	/**
	 * 요금조건을 가져옵니다..
	 * 
	 * @return 요금조건
	 */
	public String getPeople() {
		return this.people;
	}

	/**
	 * 경유여부을 설정합니다..
	 * 
	 * @param route
	 *            경유여부
	 */
	public void setRoute(String route) {
		this.route = route;
	}

	/**
	 * 경유여부을 가져옵니다..
	 * 
	 * @return 경유여부
	 */
	public String getRoute() {
		return this.route;
	}

	/**
	 * 출발시간을 설정합니다..
	 * 
	 * @param stime
	 *            출발시간
	 */
	public void setStime(String stime) {
		this.stime = stime;
	}

	/**
	 * 출발시간을 가져옵니다..
	 * 
	 * @return 출발시간
	 */
	public String getStime() {
		return this.stime;
	}

	/**
	 * 도착시간을 설정합니다..
	 * 
	 * @param etime
	 *            도착시간
	 */
	public void setEtime(String etime) {
		this.etime = etime;
	}

	/**
	 * 도착시간을 가져옵니다..
	 * 
	 * @return 도착시간
	 */
	public String getEtime() {
		return this.etime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((unq == null) ? 0 : unq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TicketMembervo other = (TicketMembervo) obj;
		if (unq == null) {
			if (other.unq != null) {
				return false;
			}
		} else if (!unq.equals(other.unq)) {
			return false;
		}
		return true;
	}

}
